// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig, env } from 'prisma/config';

export default defineConfig({
  schema: 'src/shared/infra/orm/prisma/pg/schema.prisma',
  migrations: {
    path: 'src/shared/infra/orm/prisma/pg/migrations',
  },
  datasource: {
    url: env('PG_URL'),
  },
});
